import React from 'react'
import { Paper, List, ListItem, ListItemText, makeStyles, Fab, Divider } from "@material-ui/core";
import AddIcon from "@material-ui/icons/Add"

const useStyles = makeStyles((theme) =>({
    paper: {
        marginTop:"50px",
          paddingBottom: 50,
          borderTopLeftRadius:"20px",
          borderTopRightRadius:"20px",
          borderTop:"10px solid #5d1049",
          position:"relative"
        //   height:"100vh"
        },
        list: {
          marginBottom: theme.spacing(2),
        },
        fabButton: {
            position: 'sticky',
            zIndex: 1,
            // top: -30,
            bottom:10,
            left: "100%",
            // right: 100,
            margin: '0 auto',
            backgroundColor:"#5d1049"
          },
          divider: {
        
            width:"100%",
            margin: 4,
          }
}))


const messages = [
    {
      id: 1,
      primary: 'Brunch this week?',
      secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
      person: '/static/images/avatar/5.jpg',
    },
    {
      id: 2,
      primary: 'Birthday Gift',
      secondary: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
      person: '/static/images/avatar/1.jpg',
    },
    {
      id: 3,
      primary: 'Recipe to try',
      secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
      person: '/static/images/avatar/2.jpg',
    },
    {
      id: 4,
      primary: 'Yes!',
      secondary: 'I have the tickets to the ReactConf for this year.',
      person: '/static/images/avatar/3.jpg',
    },
    {
      id: 5,
      primary: "Doctor's Appointment",
      secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
      person: '/static/images/avatar/4.jpg',
    },
    {
      id: 6,
      primary: 'Discussion',
      secondary: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.`,
      person: '/static/images/avatar/5.jpg',
    },
    {
      id: 7,
      primary: 'Summer BBQ',
      secondary: `Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill.`,
      person: '/static/images/avatar/1.jpg',
    },{
        id: 8,
        primary: 'Brunch this week?',
        secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
        person: '/static/images/avatar/5.jpg',
      },
      {
        id: 9,
        primary: 'Birthday Gift',
        secondary: `Do you have a suggestion for a good present for John on his work
          anniversary. I am really confused & would love your thoughts on it.`,
        person: '/static/images/avatar/1.jpg',
      },
      {
        id: 10,
        primary: 'Recipe to try',
        secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
        person: '/static/images/avatar/2.jpg',
      },
      {
        id: 11,
        primary: 'Yes!',
        secondary: 'I have the tickets to the ReactConf for this year.',
        person: '/static/images/avatar/3.jpg',
      },
      {
        id: 12,
        primary: "Doctor's Appointment",
        secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
        person: '/static/images/avatar/4.jpg',
      },
      {
        id: 13,
        primary: 'Discussion',
        secondary: `Menus that are generated by the bottom app bar (such as a bottom
          navigation drawer or overflow menu) open as bottom sheets at a higher elevation
          than the bar.`,
        person: '/static/images/avatar/5.jpg',
      },
      {
        id: 14,
        primary: 'Summer BBQ',
        secondary: `Who wants to have a cookout this weekend? I just got some furniture
          for my backyard and would love to fire up the grill.`,
        person: '/static/images/avatar/1.jpg',
      },
  ];
  

const WordList = () => {
    
    const classes = useStyles()


    return (
        <React.Fragment>
             <Paper square className={classes.paper}>
        {/* <Typography className={classes.text} variant="h5" gutterBottom>
          Inbox
        </Typography> */}
        <List className={classes.list}>
          {messages.map(({ id, primary, secondary, person }) => (
            <React.Fragment key={id}>
              {/* {id === 1 && <ListSubheader className={classes.subheader}>Today</ListSubheader>}
              {id === 3 && <ListSubheader className={classes.subheader}>Yesterday</ListSubheader>} */}
              <ListItem button>
                {/* <ListItemAvatar>
                  <Avatar alt="Profile Picture" src={person} />
                </ListItemAvatar> */}
                <ListItemText primary={primary} secondary={secondary} />
              </ListItem>
              <Divider className={classes.divider} orientation="horizontal" />
            </React.Fragment>
          ))}
        </List>
      <Fab  aria-label="add" className={classes.fabButton}>
            <AddIcon style={{color:"#fff"}}/>
          </Fab>
      </Paper>
        </React.Fragment>
    )
}

export { WordList }
